### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by fedor-chervinskii** [fedor-chervinskii/spermatozoids#1]
1. Heuristics to try to improve the performance of the NN:
   - **1.1 Data augmentation:**
     - [x] 1.1.1 Fill the corners with a background after rotations
     - [ ] 1.1.2 Images shifting
     - [x] 1.1.3 Mean subtraction
   - **1.2 NN architecture:**
     - [ ] 1.2.1 Transfer learning with filters, pretrained on MNIST
2. Performance evaluation
   - [ ] 2.1 script generating ROC-curve
